updates to sb-upgrade and changelog to reflect nhl-led-scoreboard repo

diff --git a/scripts/sbtools/sb-upgrade b/scripts/sbtools/sb-upgrade
--- a/scripts/sbtools/sb-upgrade
+++ b/scripts/sbtools/sb-upgrade
@@ -3,8 +3,9 @@
 # https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/upgrade.sh
 
 #cd /home/pi/nhl-led-scoreboard
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-cd "${DIR}"
+Uncomment for running out of the repository scripts/sbtools directory
+#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+#cd "${DIR}"
 
 # Use colors, but only if connected to a terminal
 # and that terminal supports them.
@@ -74,29 +75,41 @@ if git pull --rebase --stat origin master; then
     git config nhl-led-scoreboard.lastVersion "$last_commit"
 
     # Display changelog with less if available, otherwise just print it to the terminal
-    #if [[ "$1" = --interactive ]]; then
-      changelog.sh HEAD "$last_commit"
+    if [[ $ret -eq 0 ]]; then
+      #"/home/pi/sbtools/changelog.sh" HEAD "$last_commit"
+      # Uncomment line below if running from repository scripts/sbtools directory
+      scripts/sbtools/changelog.sh HEAD "$last_commit"
     #fi
 
-    #printf "${BLUE}%s \`${BOLD}%s${RESET}${BLUE}\`${RESET}\n" "You can see the changelog anytime with" "sb-changelog"
-
-    #Check to see if the requirements.txt has changed, if so, run the pip3 install -r requirements.txt again
-    if ! git diff -s --exit-code HEAD~1 HEAD requirements.txt; then
-       printf "${GREEN}%s${RESET}\n" "New python library requirements for this version, installing now"
-       sudo pip3 install -r requirements.txt
+    #Comment out if running from repositories scripts/sbtools directory
+    printf "${BLUE}%s \`${BOLD}%s${RESET}${BLUE}\`${RESET}\n" "You can see the changelog anytime with" "sb-changelog"
+   if [[ -a requirements.txt ]]; then
+       #Check to see if the requirements.txt has changed, if so, run the pip3 install -r requirements.txt again
+       if ! git diff -s --exit-code HEAD~1 HEAD requirements.txt; then
+          printf "${GREEN}%s${RESET}\n" "New python library requirements for this version, installing now"
+          sudo pip3 install -r requirements.txt
+       else
+          printf "${YELLOW}%s${RESET}\n" "No new python libraries required to be installed."
+       fi
     else
-       printf "${YELLOW}%s${RESET}\n" "No new python libraries required to be installed."
+         printf "${RED}%s${RESET}\n" "No python requirements.txt found"
     fi
 
-    #Check to see if the aptfile has changed, if so, run the sudo aptfile again
-    if ! git diff -s --exit-code HEAD~1 HEAD aptfile; then
-       printf "${GREEN}%s${RESET}\n" "New apt requirements for this version, installing now"
-       sudo scripts/aptfile apt-requirements
+    #Check to see if the apt-requirements has changed, if so, run the sudo aptfile apt-requirements again
+    if [[ -a apt-requirements ]]; then 
+       if ! git diff -s --exit-code HEAD~1 HEAD apt-requirements; then
+          printf "${GREEN}%s${RESET}\n" "New apt requirements for this version, installing now"
+          #sudo /usr/local/bin/aptfile apt-requirements
+	  #Uncomment if running from repo scripts/sbtools, comment out above line
+          sudo scripts/sbtools/aptfile apt-requirements
+       else
+          printf "${YELLOW}%s${RESET}\n" "No new apt required to be installed."
+      fi
     else
-       printf "${YELLOW}%s${RESET}\n" "No new apt required to be installed."
+          printf "${RED}%s${RESET}\n" "No apt-requirements found"
     fi
   fi
-
+  fi
   printf "${BLUE}%s${RESET}\n" "$message"
 else
   ret=$?
